sudo: required
services:
  - docker

before_install:
  - docker build -t tommyg115/docker-react -f Dockerfile.dev .

# Use below script to run tests with create react app with travis

script:
  - docker run -e CI=true tommyg115/docker-react npm run test
