sudo: required
services:
  - docker

before_install:
  - docker build -t tommyg115/docker-react -f Dockerfile.dev .

# Use below script to run tests with create react app with travis

script:
  - docker run -e CI=true tommyg115/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker1"
  env: "Docker1-env"
  # zip file for code
  bucket_name: "elasticbeanstalk-us-east-2-478533612558"
  bucket_path: "docker1"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"

